### PR TITLE
OpenId

### PR DESCRIPTION
**Pull request by rearguard-hu**
Add OpenID Connect support 
Add some configuration

### CODE REVIEW

**Comment by ariacom** [comment]
Great, thank you, can you provide test cases to validate the code ? How can we test this feature ?
Can you also write you comments in english, thank you.

**Comment by ariacom** [comment]
I have made some small fix, however it seems thats the previous "Basic Authentication" is not working anymore.
Can you check this  please ?

**Comment by rearguard-hu** [comment]
This has been resolved through the new configuration, and the content has been submitted for merging



---- 回复的原邮件 ----
| 发件人 | Seal ***@***.***> |
| 日期 | 2022年03月03日 18:09 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [ariacom/Seal-Report] OpenId (PR #63) |

I have made some small fix, however it seems thats the previous "Basic Authentication" is not working anymore.
Can you check this please ?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ariacom** [comment]
Ok, it is difficult to check the implementation. You should provide a version that works in a basic case.
Thank you.

**Pull request merged**
