### PR TITLE
Added configuration for additional providers - Added SqlServer Provider.

### PR DESCRIPTION
**Pull request by przemyslawandruszewski**
Added SQL Server as an option to store session in the SQL Server database in configured way.

### CODE REVIEW

**Comment by ariacom** [comment]
Thank you for the contribution, can you explain in what scenario we should use SQL Server  Sessions ?
Can you provide a sample of configuration and how can we test these changes...

**Comment by przemyslawandruszewski** [comment]
Hello,
Thank you for looking at the code. 
The scenario I was missing was when you have production setup consisting of two nodes load balanced with the round Robin. Being logged on one node means not Being logged on second node as currently the session is stored only in the memory and is not moved.
When compare to .Net framework, in Old version you as developer you Could chose the provider for session in web .config which is not the case right now with core.

**Comment by ariacom** [comment]
Thank for the documentation, perhaps it is better to integrate this in the SealDocumentation (https://sealreport.org/Server#lineConfiguration), if you can do it it would be great....
if you have time, the implementation for .Net Framework could be also great.

I will mainly test no regression for the 6.0.

**Comment by przemyslawandruszewski** [comment]
Thanks for pointing me to move the docs to global documentation. That should help centralize it.
Regarding the implementation of session storage for .NET Framework I think we should do nothing about cause as I can see currently it is configured here:
https://github.com/ariacom/Seal-Report/blob/master/Projects/SealWebServer/Web.config#L52
to default settings.
Moving session to SQL in .NET Framework was a bit easier cause to move it you had to just change settings in web.config:
<sessionState
    mode="SQLServer"
    sqlConnectionString="data source=127.0.0.1;user id=<username>;password=<strongpassword>"
    cookieless="false"
    timeout="20"
/>

So I am not sure we should do anything else about it.

How you see the possibilities of approving this change from dotnet core perspective? We are very interested using Seal Report in our solution but that was potential blocking point.

**Comment by ariacom** [comment]
I merged the pull request and made a quick test with the Web Server, it seems ok with no regression...
However I did not test the SQLServer sessions...

**Comment by ariacom** [comment]
Hello, it looks like there is a regression for this implementation in .Net 6, can you check please ?
The tool to create the table does not work as well 'dotnet  tool  install --global  dotnet-sql-cache'
thanks in advance.

**Pull request merged**
